#ifndef _CILKPRACE_ABLATION_CONFIG_H
#define _CILKPRACE_ABLATION_CONFIG_H

// Generated by tools/ablate.py -- do not edit by hand while a sweep is running.
// Config: no-CACHE_ALIGN
#define CILKPRACE_ABL_CACHE_ALIGN 0

#endif /* _CILKPRACE_ABLATION_CONFIG_H */
