#ifndef _CILKPRACE_ABLATION_CONFIG_H
#define _CILKPRACE_ABLATION_CONFIG_H

// Generated by tools/ablate.py -- do not edit by hand while a sweep is running.
// Config: baseline

#endif /* _CILKPRACE_ABLATION_CONFIG_H */
